### ISSUE TITLE
How do you theme this? Particularly change colors.

### ISSUE THREAD

**Issue by vans163** [cssninjaStudio/krypton#1]
How do you theme this? Particularly change colors.

All the colors and grandients seem hardcoded into the scss files, is there a generator available?

**Comment by cssninjaStudio** [comment]
Well iam sorry, but there a no variable associated with gradients, because they also include background images. It can be quite restraining for styling. However, this is meant to be a dark theme. You'll have to dig in the SCSS to change the colors to your convenience. Although, i might consider reworking this to be more theming friendly in a future update.

**Comment by vans163** [comment]
Its just all purple and dark, it serves as a good example of your work, but unless your products theme is dark purple its quite difficult to change (requires changes to .svg circle images that are purple too)

**Comment by cssninjaStudio** [comment]
> Just dig into the SCSS/SASS, its way better if you want to change the theme

👍  I guess everything has been said, iam closing this . If however you want something with easy theming, you should look at our 1st freebie, Fresh. It has theme variables that are customizable out of the box.
